name: Terraform Deploy

on:
  push:
    branches:
      - develop
      - staging
      - main
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-deploy.yml'

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5

      # Paso 1: Determinar el entorno y establecer variables de ambiente
      - name: Set environment variables
        id: set-env
        run: |
          CURRENT_BRANCH="${GITHUB_REF_NAME}"
          echo "Current branch is $CURRENT_BRANCH"
          ENV_TYPE="UNKNOWN"

          # Seleccionar entorno según la rama actual usando 'case'
          case "$CURRENT_BRANCH" in
            develop)
              ENV_TYPE="DEVELOP"
              echo "TF_VAR_environment=develop" >> $GITHUB_ENV
              echo "TF_VAR_ingest_bucket_name=${{ secrets.DEVELOP_INGEST_BUCKET_NAME }}" >> $GITHUB_ENV
              echo "TF_VAR_processed_bucket_name=${{ secrets.DEVELOP_PROCESSED_BUCKET_NAME }}" >> $GITHUB_ENV
              ;;
            staging)
              ENV_TYPE="STAGING"
              echo "TF_VAR_environment=staging" >> $GITHUB_ENV
              echo "TF_VAR_ingest_bucket_name=${{ secrets.STAGING_INGEST_BUCKET_NAME }}" >> $GITHUB_ENV
              echo "TF_VAR_processed_bucket_name=${{ secrets.STAGING_PROCESSED_BUCKET_NAME }}" >> $GITHUB_ENV
              ;;
            main)
              ENV_TYPE="MAIN"
              # En el caso de que 'main' represente producción
              echo "TF_VAR_environment=production" >> $GITHUB_ENV
              echo "TF_VAR_ingest_bucket_name=${{ secrets.MAIN_INGEST_BUCKET_NAME }}" >> $GITHUB_ENV
              echo "TF_VAR_processed_bucket_name=${{ secrets.MAIN_PROCESSED_BUCKET_NAME }}" >> $GITHUB_ENV
              ;;
          esac

          # Exportar el tipo de entorno para pasos posteriores
          echo "env_type=$ENV_TYPE" >> $GITHUB_OUTPUT

          # Finalizar la ejecución si el entorno es desconocido
          if [ "$ENV_TYPE" = "UNKNOWN" ]; then
            echo "Unsupported branch: $CURRENT_BRANCH"
            exit 1
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      # Paso 2: Inicializar Terraform con configuración del backend
      - name: Terraform Init
        if: steps.set-env.outputs.env_type != 'UNKNOWN'
        working-directory: ./terraform
        env:
          TF_VAR_aws_region: ${{ secrets.AWS_DEFAULT_REGION }}
          BUCKET_NAME: ${{ secrets.TF_STATE_BUCKET }}
        run: |
          terraform init \
            -backend-config="bucket=${BUCKET_NAME}" \
            -backend-config="key=${{ github.ref_name }}/terraform.tfstate" \
            -backend-config="region=${{ secrets.AWS_DEFAULT_REGION }}" \
            -backend-config="encrypt=true"

      # Paso 3: Ejecutar Terraform Plan
      - name: Terraform Plan
        if: steps.set-env.outputs.env_type != 'UNKNOWN'
        working-directory: ./terraform
        env:
          TF_VAR_aws_region: ${{ secrets.AWS_DEFAULT_REGION }}
        run: terraform plan -no-color

      # Paso 4: Ejecutar Terraform Apply (solo en push)
      - name: Terraform Apply
        if: steps.set-env.outputs.env_type != 'UNKNOWN' && github.event_name == 'push'
        working-directory: ./terraform
        env:
          TF_VAR_aws_region: ${{ secrets.AWS_DEFAULT_REGION }}
        run: terraform apply -auto-approve
